<div class="card main">
    <div class="card-header">
        Google Authenticator
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <img src="<?= $qr ?>" style="width:100%">
            </div>
            <div class="col-md-8">
                <div class="alert alert-info">
                    Please use your Google Authenticator application to scan this
                    QR code to connect your account with the dashboard.
                </div>
            </div>
        </div>
    </div>
</div>
